// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"MenuCallCommonMZ","status":true,"description":"メニュー開閉の代わりにコモンイベント実装するプラグイン","parameters":{"CommonEventOpen":"2","CommonEventClose":"3","CommonEventSwitch":"1","EventMoveOk":"2"}}
];
